In [3]:
import pandas as pd
df = pd.read_csv(r"C:\users\perfect\documents\retail-sales-etl\data\retail_orders.csv")
df.head()

   order_id customer   product  quantity   price  order_date    city
0       101     Asha    Laptop         1  50,000  01-10-2026    Pune
1       102    Rahul     Mouse         2    2500  02-10-2026  Mumbai
2       103    Priya  Keyboard         1    1500  02-10-2026    Pune
3       104     Asha     Mouse         3    3500  03-10-2026    Pune
4       105     Amit    Laptop         1   50000  04-10-2026   Delhi

In [6]:
#  Check column names
df.shape

(10, 7)

In [7]:
# Check data types and missing values
df.columns

Index(['order_id', 'customer', 'product', 'quantity', 'price', 'order_date',
       'city'],
      dtype='str')

In [8]:
# Get basic statistics
df.describe()

        order_id   quantity
count   10.00000  10.000000
mean   105.50000   1.800000
std      3.02765   1.032796
min    101.00000   1.000000
25%    103.25000   1.000000
50%    105.50000   1.500000
75%    107.75000   2.000000
max    110.00000   4.000000

In [9]:
df.isnull().sum()

order_id      0
customer      0
product       0
quantity      0
price         0
order_date    0
city          0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df["order_id"].duplicated().sum()

np.int64(0)

In [12]:
df.dtypes

order_id      int64
customer        str
product         str
quantity      int64
price           str
order_date      str
city            str
dtype: object

In [13]:
df["customer"] = df["customer"].str.strip()
df["product"] = df["product"].str.strip()
df["city"] = df["city"].str.strip()

df.head()

   order_id customer   product  quantity   price  order_date    city
0       101     Asha    Laptop         1  50,000  01-10-2026    Pune
1       102    Rahul     Mouse         2    2500  02-10-2026  Mumbai
2       103    Priya  Keyboard         1    1500  02-10-2026    Pune
3       104     Asha     Mouse         3    3500  03-10-2026    Pune
4       105     Amit    Laptop         1   50000  04-10-2026   Delhi

In [14]:
df["order_date"] = pd.to_datetime(df["order_date"])
df.dtypes

order_id               int64
customer                 str
product                  str
quantity               int64
price                    str
order_date    datetime64[us]
city                     str
dtype: object

In [15]:
df["total_amount"] = df["quantity"] * df["price"]
df[["order_id","product","quantity","price","total_amount"]].head()

   order_id   product  quantity   price  total_amount
0       101    Laptop         1  50,000        50,000
1       102     Mouse         2    2500      25002500
2       103  Keyboard         1    1500          1500
3       104     Mouse         3    3500  350035003500
4       105    Laptop         1   50000         50000

In [16]:
df["price"] = df["price"].str.replace(",", "", regex=False).astype(int)

In [17]:
df.dtypes

order_id                 int64
customer                   str
product                    str
quantity                 int64
price                    int64
order_date      datetime64[us]
city                       str
total_amount               str
dtype: object

In [18]:
df["total_amount"] = df["quantity"] * df["price"]

In [19]:
df[["order_id","product","quantity","price","total_amount"]].head()

   order_id   product  quantity  price  total_amount
0       101    Laptop         1  50000         50000
1       102     Mouse         2   2500          5000
2       103  Keyboard         1   1500          1500
3       104     Mouse         3   3500         10500
4       105    Laptop         1  50000         50000

In [20]:
df.isnull().sum()

order_id        0
customer        0
product         0
quantity        0
price           0
order_date      0
city            0
total_amount    0
dtype: int64

In [21]:
df[(df["quantity"] <= 0) | (df["price"] <= 0)]

Empty DataFrame
Columns: [order_id, customer, product, quantity, price, order_date, city, total_amount]
Index: []

In [22]:
df[df["order_id"].duplicated(keep=False)]

Empty DataFrame
Columns: [order_id, customer, product, quantity, price, order_date, city, total_amount]
Index: []

In [23]:
df.head(10)

,order_id,customer,product,quantity,price,order_date,city,total_amount
0,101,Asha,Laptop,1,50000,2026-01-10,Pune,50000
1,102,Rahul,Mouse,2,2500,2026-02-10,Mumbai,5000
2,103,Priya,Keyboard,1,1500,2026-02-10,Pune,1500
3,104,Asha,Mouse,3,3500,2026-03-10,Pune,10500
4,105,Amit,Laptop,1,50000,2026-04-10,Delhi,50000
5,106,rahul,Keyboard,2,1500,2026-05-10,Mumbai,3000
6,107,Sneha,Monitor,1,12000,2026-05-10,Pune,12000
7,108,Neha,Mouse,4,500,2026-06-10,Mumbai,2000
8,109,Amit,Keyboard,2,1500,2026-07-10,Delhi,3000
9,110,Priya,Laptop,1,50000,2026-08-10,Pune,50000

In [26]:
df.to_csv(r"C:\users\perfect\documents\retail-sales-etl\data\cleaned_orders.csv", index=False)

In [30]:
df.to_csv(r"C:\users\perfect\documents\retail-sales-etl\data\cleaned_orders.csv", index=False)
print("File saved successfully!")

File saved successfully!